[build]
  command = "bun run build"
  publish = ".output/public"

[build.environment]
  NITRO_PRESET = "static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "bun run dev"
  port = 3000
